spring.application.name=Reservas_Luderia

spring.datasource.url=jdbc:postgresql://localhost:5432/db_reservas
spring.datasource.username=postgres
spring.datasource.password=Lucena08
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

catalogo_jogos.url=localhost:8081
usuario.url=localhost:8080